In [9]:
# n = 'aditya' is a keyword argument.
def hello3(n='Aditya'):
    print('Hello',n)

In [10]:
hello3('India')

Hello India


In [11]:
hello3()

Hello Aditya


In [12]:
# n is a positional argument.
def hello2(n):
    print('Hello',n)

In [13]:
hello2()

TypeError: hello2() missing 1 required positional argument: 'n'

In [14]:
# wrong order of keyword argument
def two_args(x=1,y):
    print(x+y)

SyntaxError: non-default argument follows default argument (1181697275.py, line 2)

In [15]:
#return a value.
def sq(x):
    return x**2

In [18]:
sq(3)

9

In [17]:
y = sq(4)
print(y)
type(y)

16


int

In [20]:
# Return multiple values from a function
def sq_cu(x):
    return x**2, x**3

In [21]:
s,c = sq_cu(5)

In [22]:
s

25

In [23]:
c

125

## Name space
+ Functions can access variables created inside the function and also variables created outside the function in higher scopes.
+ The technical word describing variable scope in python is namespace.
+ Any variables which are assigned within a function are by default assigned to the local namespace.
+ The local namespce is created when a function is called, and is immediately populated by the functon arguments.
+ After the execution of a function is finished the local namespace is destroyed

In [24]:
def scope1():
    a = 10 
    print(a)

In [25]:
a = 5
scope1()

10


In [26]:
print(a)

5


In [17]:
import numpy as np

In [4]:
# array of ones
# one dimenaional array
arr1a = np.ones(5)
arr1a

array([1., 1., 1., 1., 1.])

In [5]:
arr1b = np.ones((3,4))
arr1b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Q. What is vectorization?
+ Array allows us to perform batch operations on data without writing for loops in numpy. This is called Vectorization.
+ Arithmetic operations between arrays of the same size apply the operation element-wise.
+ Arithmetic operations between a scalar and an array apply the operation to each element of the array.

In [6]:
arr1 = np.array([2,4],[6,8])
arr2 = np.array([1,1],[2,2])
print(arr1)
print(arr2)

TypeError: Field elements must be 2- or 3-tuples, got '6'

In [42]:
#A slice of a numpy array is a viem, not a copy of that part of the array.
arr1 = np.array([1,2,3,4,5,6])
l = [10,20,30,40,50,60]

In [41]:
sl = l[1:3]
sl

[20, 30]

In [40]:
sl = [5,6]

In [39]:
sl

[5, 6]

In [38]:
l

[10, 20, 30, 40, 50, 60]

In [37]:
sa = arr1[1:3]

In [35]:
sa

10

In [44]:
sa[:] = 10
sa

array([10, 10])

In [46]:
arr1

array([1, 2, 3, 4, 5, 6])

In [47]:
#indexing,slicing a 1d array

In [48]:
arr=np.array([2,4,6,8,10])

In [49]:
#Third element
arr[2]

6

In [50]:
#slice of 3rd and 4th element
arr[2:4]

array([6, 8])

In [51]:
arr[:3]

array([2, 4, 6])

In [53]:
arr[3:]

array([ 8, 10])

In [54]:
arr[:0]

array([], dtype=int32)

In [55]:
arr[3:5]

array([ 8, 10])

In [56]:
arr[:5]

array([ 2,  4,  6,  8, 10])

## Indexing and slicing a 2d array

In [58]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
# Axis 0 is rows,axis 1 is columns.
arr.shape

(3, 3)

In [60]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2.shape

(4, 3)

In [61]:
arr2[1]

array([4, 5, 6])

In [62]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a= arr2[1]
print(a.shape)
print(a.ndim)

(3,)
1


In [69]:
b = arr2[:2]
print(b.shape)
print(b.ndim)

(2, 3)
2


In [73]:
# Recursively use indexes to access elements.
arr2[1]

array([4, 5, 6])

In [75]:
arr2[1][1]

5

In [77]:
arr2[3][2]

12

In [78]:
arr2[1,1]

5

In [79]:
arr2[3,2]

12

In [81]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [83]:
arr2[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [3]:
n = int(input())
i = 1
c = 0
while i <= n:
    if n % i == 0:
        c = c+1
    i += 1
if c == 2:
    print("Prime number")
else:
    print("Not a prime Number")

17
Prime number


In [1]:
n = int(input())
i = 1
while i <= n:
    if i % 2 == 0:
        print(i)
    i += 1

10
2
4
6
8
10


In [13]:
import numpy as np

In [14]:
from numpy.linalg import inv,det
a = np.array([[4,2],[1,3]])
A = inv(a)
A

array([[ 0.3, -0.2],
       [-0.1,  0.4]])

In [15]:
a*A # WRONG

array([[ 1.2, -0.4],
       [-0.1,  1.2]])

In [16]:
np.dot(a,A)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00]])

In [19]:
b = np.array([[2,0,0],[0,5,0],[0,0,10]])
B= inv(b)
B

array([[0.5, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.1]])

# Essential Functioanlity
### 1)Reindexing a Series
### 2)Selection from a Series and .loc[] and .loc[] attributes
### 3)Dropping entries from an axis.
### 4)Alignment of labels in arthemetic operations

In [5]:
import pandas as pd

In [16]:
df = pd.DataFrame({'A':[1,2,3],'B':[11,22,33],'C':[21,22,23]},index=['X','Y','Z'])

In [17]:
df

A   B   C
X  1  11  21
Y  2  22  22
Z  3  33  23

In [21]:
# reindexing rows
df.reindex(['Y','X'])

A   B   C
Y  2  22  22
X  1  11  21

In [22]:
# reindexing columns
df.reindex(['C','A'])

A   B   C
C NaN NaN NaN
A NaN NaN NaN

In [23]:
df.reindex(columns = ['C','A'])

C  A
X  21  1
Y  22  2
Z  23  3

In [25]:
# Reindexing rows and columns
df.reindex(index=['Z','X'],columns = ['C','B'])

C   B
Z  23  33
X  21  11

In [30]:
# Dropping an entry Creates a new object.
df.drop(['X'])

A   B   C
Y  2  22  22
Z  3  33  23

In [32]:
df.drop(index=['X'],columns=['C'])

A   B
Y  2  22
Z  3  33

In [37]:
# Alignment of DataFrame labels in arithmetic operations
df1 = pd.DataFrame({'A':[1,2],'B':[3,4]},index=['X','Y'])
df1

A  B
X  1  3
Y  2  4

In [38]:
df2 = pd.DataFrame({'A':[10,20],'C':[50,60]},index=['X','Z'])
df2

A   C
X  10  50
Z  20  60

In [39]:
# Union of row labels and column lables
df1+df2

A   B   C
X  11.0 NaN NaN
Y   NaN NaN NaN
Z   NaN NaN NaN

In [26]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [30]:
from numpy import *
arr1 = array('i',[1,2,3,4,5])
arr1.remove(1)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [47]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]},index=['x','y'])
df2=pd.DataFrame({'B':[10,20],'B':[50,60]},index=['y','x'])

In [50]:
df2
df1

A  B
x  1  3
y  2  4

In [49]:
df1+df2

A   B
x NaN  63
y NaN  54

In [4]:
import pandas as pd

In [5]:
s1 = pd.Series([2,4,6,8])
s2 = pd.Series([1,2,1,2])
s1+s2

0     3
1     6
2     7
3    10
dtype: int64

In [6]:
s1/s2

0    2.0
1    2.0
2    6.0
3    4.0
dtype: float64

In [7]:
s1*s2

0     2
1     8
2     6
3    16
dtype: int64

# Arithmetic methods for Series and Data Frame 

In [9]:
s1.add(s2)

0     3
1     6
2     7
3    10
dtype: int64

In [10]:
s1.div(s2)

0    2.0
1    2.0
2    6.0
3    4.0
dtype: float64

In [11]:
s1.mul(s2)

0     2
1     8
2     6
3    16
dtype: int64

In [12]:
1/s1

0    0.500000
1    0.250000
2    0.166667
3    0.125000
dtype: float64

# r version of methods reverses the argument of the objects

In [15]:
s1.radd(s2)

0     3
1     6
2     7
3    10
dtype: int64

In [17]:
s2.add(s1)

0     3
1     6
2     7
3    10
dtype: int64

In [18]:
s1.rdiv(s2) 

0    0.500000
1    0.500000
2    0.166667
3    0.250000
dtype: float64

# Operations brtween a DataFrame and a Series

In [4]:
df = pd.DataFrame({'A':[1,2,3],'B':[2,3,4]},index=['X','Y','Z'])

In [24]:
df

A  B
X  1  2
Y  2  3
Z  3  4

In [32]:
s1 = pd.Series([10,20],index=['A','B'])
s2 = pd.Series([5,10,15],index=['X','Y','Z'])

In [33]:
df+s1 

A   B
X  11  22
Y  12  23
Z  13  24

In [34]:
df+s2

A   B   X   Y   Z
X NaN NaN NaN NaN NaN
Y NaN NaN NaN NaN NaN
Z NaN NaN NaN NaN NaN

In [37]:
df.add(s2,axis=0) 

A   B
X   6   7
Y  12  13
Z  18  19

## Summarizing and computing descriptive statistics

In [42]:
## Series methods return a scalar
s2.sum()

30

In [43]:
s2.mean()

10.0

In [44]:
s2.median()

10.0

In [45]:
df.sum()

A    6
B    9
dtype: int64

In [46]:
df.mean()

A    2.0
B    3.0
dtype: float64

In [47]:
df.sum(axis=1)

X    3
Y    5
Z    7
dtype: int64

In [49]:
df.mean(axis=1)

X    1.5
Y    2.5
Z    3.5
dtype: float64

In [2]:
import pandas as pd

In [6]:
df = pd.DataFrame({'A':[2,3,4],'B':[3,4,5]},index=['X','Y','Z'])

In [7]:
df.mean()

A    3.0
B    4.0
dtype: float64

In [8]:
df.sum()

A     9
B    12
dtype: int64

## Reductions

In [9]:
df.cumsum()

A   B
X  2   3
Y  5   7
Z  9  12

In [11]:
df.idxmin()

A    X
B    X
dtype: object

In [12]:
df2 = pd.DataFrame({'A':[5,3,2,4],'B':[10,1,7,8]})

In [13]:
df2.idxmin()

A    2
B    1
dtype: int64

In [14]:
df2.idxmin(axis='columns')

0    A
1    B
2    A
3    A
dtype: object

In [15]:
df2.idxmax()

A    0
B    0
dtype: int64

In [16]:
df3 = pd.DataFrame({'A':[5,10,15],'B':['Hello','World','India']})

In [17]:
df3

A      B
0   5  Hello
1  10  World
2  15  India

In [18]:
df3.describe()

A
count   3.0
mean   10.0
std     5.0
min     5.0
25%     7.5
50%    10.0
75%    12.5
max    15.0

In [19]:
df2.describe()

A          B
count  4.000000   4.000000
mean   3.500000   6.500000
std    1.290994   3.872983
min    2.000000   1.000000
25%    2.750000   5.500000
50%    3.500000   7.500000
75%    4.250000   8.500000
max    5.000000  10.000000

In [20]:
import pandas as pd

In [21]:
import numpy as np

In [24]:
df = pd.read_csv("first.csv")

In [25]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [1]:
import pandas as pd

+ pandas treats first row as column headings.
+ Pandas adds a row index it all columns have names and values.
+ If the first row has 1 less element than column of all other rows is treated as a row index.

In [3]:
df = pd.DataFrame({'X':[1,2,3],'Y':[4,5,6],'Z':[7,8,9]},index=['A','B','C'])

In [4]:
df

X  Y  Z
A  1  4  7
B  2  5  8
C  3  6  9

In [5]:
df = pd.read_csv('second.csv')

In [6]:
df

Unnamed: 0  X  Y  Z
0          A  1  4  7
1          B  2  5  8
2          C  3  6  9

In [15]:
df = pd.read_csv('second.csv',index_col=0)

In [16]:
df

X  Y  Z
A  1  4  7
B  2  5  8
C  3  6  9

In [17]:
df = pd.read_csv('third.csv',index_col='ID')

In [18]:
df

A  B  C
ID         
X   1  4  7
Y   2  5  8
Z   3  6  9

### HANDING NULL VALUES
+ PAndas treats missing values, empty strings and a few sentinal values such as NA or NULL as null values.

In [20]:
df = pd.read_csv('fouth.csv')

In [21]:
df

A    B    C
0  1  4.0  7.0
1  2  NaN  8.0
2  3  6.0  NaN

+ To read large data sets,  we can use the chunksize argument to load a few rows at a time.

In [22]:
# read 2 rows at a time.
# calculate sum of value of those 2 rows.
# add to grand total value.
# Add nuber of rows to grand total rows.
# Complete average of grand total value/grand total rows.


# Data Cleaning   and Preparation (Unit - 3, 2nd Chapter)

## 1)Handling Missing Values.
### Identifying missing values.
+ In numeric data ,pythoon represents mssing values using NaN.(Not a Number)
+ Python refers to all missing data as NA.(NA - Not a avaliable)
+ Python's  "None object" is also treated as NA.
+ The isna() and notna() functions/methods help idnetify missing data
### Removing missing values.
+ Removing missing data with dropna().
+ KEEP rows with threshold number of values.
### Filling in data in place of missing values.
+ Pandas .fillna() method helps us fill in values in place of missing data.
+ Fill in missing data using column-specific values.pass a dict
+ Column-wise means
## 2)Data Transformation.
### Removing duplicates
+ Remove duplicates with drop_duplicates() method
+ Identifying dulicates using .duplicated() method

### Transform data using a function
+ Discretization and binning
+ Permutation and random sampling.
### Replacing values
+ all occorrences of a value
+ list of values
+ column are
### Replace axis indexes
+ replacing by assignment modifies the object.
+ using .rename() method creates a new object.
+ We can change selected labels using a dict.
## 3)String Operations

## Handling Missing Values

In [1]:
# The isna() and notna() functions/methods help idnetify missing data.
import pandas as pd
import numpy as np
s = pd.Series([2,np.nan,5])

In [2]:
s

0    2.0
1    NaN
2    5.0
dtype: float64

In [3]:
s.isna()

0    False
1     True
2    False
dtype: bool

In [4]:
s2 = pd.Series(["hello","World",None])
s2

0    hello
1    World
2     None
dtype: object

In [6]:
s2.isna()

0    False
1    False
2     True
dtype: bool

In [9]:
pd.isna(s)

0    False
1     True
2    False
dtype: bool

In [10]:
pd.isna(s2)

0    False
1    False
2     True
dtype: bool

In [15]:
df = pd.DataFrame({'A':[1,2,np.nan],'B':[3,np.nan,np.nan],'C':[4,np.nan,np.nan]},index = [1,2,3])

In [16]:
df

A    B    C
1  1.0  3.0  4.0
2  2.0  NaN  NaN
3  NaN  NaN  NaN

In [17]:
# Remove all missing values with dropna()
df.dropna()

A    B    C
1  1.0  3.0  4.0

In [19]:
# Removing rows with ALLL missing values.
df.dropna(how = "all")

A    B    C
1  1.0  3.0  4.0
2  2.0  NaN  NaN

In [27]:
df['D'] = np.nan

In [28]:
df

A    B    C   D
1  1.0  3.0  4.0 NaN
2  2.0  NaN  NaN NaN
3  NaN  NaN  NaN NaN

In [30]:
# KEEP rows with threshold number of values.
df.dropna(thresh=1)

A    B    C   D
1  1.0  3.0  4.0 NaN
2  2.0  NaN  NaN NaN

In [31]:
df.dropna(thresh=3)

A    B    C   D
1  1.0  3.0  4.0 NaN

In [32]:
df.dropna(thresh=2)

A    B    C   D
1  1.0  3.0  4.0 NaN

In [34]:
df.dropna(axis = 'columns',how = 'all')

A    B    C
1  1.0  3.0  4.0
2  2.0  NaN  NaN
3  NaN  NaN  NaN

In [35]:
df.dropna(axis='columns',thresh=2)

A
1  1.0
2  2.0
3  NaN

In [1]:
import pandas as pd
import numpy as np

In [3]:
# Filling in missing data.
df = pd.DataFrame({'A':['Hello',np.nan,'World'],'B':[1,2,np.nan]})

In [4]:
df

A    B
0  Hello  1.0
1    NaN  2.0
2  World  NaN

In [7]:
# FIll with a single value.
df.fillna('Missing')

A        B
0    Hello      1.0
1  Missing      2.0
2    World  Missing

In [8]:
df.fillna(0)

A    B
0  Hello  1.0
1      0  2.0
2  World  0.0

In [9]:
# Fill in missing data using column-specific values.pass a dict
df.fillna({'A':'Missing','B':0})

A    B
0    Hello  1.0
1  Missing  2.0
2    World  0.0

In [11]:
df = pd.DataFrame({'A':[1,2,np.nan,6],'B':[4,np.nan,6,8]})

In [12]:
df

A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0
3  6.0  8.0

In [13]:
# Column-wise means
df.fillna(df.mean())

A    B
0  1.0  4.0
1  2.0  6.0
2  3.0  6.0
3  6.0  8.0

In [14]:
# Column-wise median
df.fillna(df.median())

A    B
0  1.0  4.0
1  2.0  6.0
2  2.0  6.0
3  6.0  8.0

## Data Transformation

In [20]:
# Identifying dulicates using .duplicated() method
df = pd.DataFrame({'A':[1,2,3,2],'B':[11,12,13,12]})
df

A   B
0  1  11
1  2  12
2  3  13
3  2  12

In [21]:
# Find duplicate rows
df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [22]:
# Remove duplicates with drop_duplicates() method
df.drop_duplicates()

A   B
0  1  11
1  2  12
2  3  13

In [24]:
df.drop_duplicates(keep = 'last')

A   B
0  1  11
2  3  13
3  2  12

In [46]:
df1 = pd.DataFrame({'A':[1,1,2],'B':[2,2,3],'C':[3,4,5]})

In [47]:
df1

A  B  C
0  1  2  3
1  1  2  4
2  2  3  5

In [27]:
df1.duplicated()

0    False
1    False
2    False
dtype: bool

+ To check for duplicates in a subset of columns, use the subset argument, passed with a list of columns.

In [41]:
df1.drop_duplicates(subset=['A','B'])

A  B  C
0  1  2  3
2  2  3  5

In [42]:
# Transforming data using a function or map
def is_even(x):
    if x%2 == 0:
        return "Even"
    else:
        return "Odd"
n = int(input())
k = is_even(n)
print(k)

ValueError: invalid literal for int() with base 10: ''

In [48]:
df1['D'] = df1['C'].map(is_even)

In [49]:
df1

A  B  C     D
0  1  2  3   Odd
1  1  2  4  Even
2  2  3  5   Odd

In [2]:
import pandas as pd
import numpy as np

In [3]:
df5 = pd.DataFrame({'A':[1,2,3],'B':[2,3,6]})
df5

A  B
0  1  2
1  2  3
2  3  6

In [5]:
# Replace all occurances of 2 with 20
df5.replace(2,20)

A   B
0   1  20
1  20   3
2   3   6

In [8]:
# Replace a list of values with corresponding elements from another list of values
df5.replace([2,3],[200,300])

A    B
0    1  200
1  200  300
2  300    6

In [9]:
# Replace 2 of column a with 20 and 2 of column b with 200 usingt dictionary
df5.replace({'A':2,'B':2},{'A':20,'B':200})

A    B
0   1  200
1  20    3
2   3    6

#### Replace axis indexes
+ replacing by assignment modifies the object.
+ using .rename() method creates a new object.
+ We can change selected labels using a dict.

In [10]:
df5.index=['x','y','z']
df5

A  B
x  1  2
y  2  3
z  3  6

In [13]:
df5.colummns = [ 'a','b']
df5

C:\Users\laksh\AppData\Local\Temp\ipykernel_1732\1175487841.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df5.colummns = [ 'a','b']


A  B
x  1  2
y  2  3
z  3  6

#### Discretization and binning

In [14]:
s = pd.Series([2,5,3,10,12,5,15])

In [15]:
# use the cut function to place values of a continuous variable into bins.
disc = pd.cut(s,bins = 3]

In [16]:
disc

0     (1.987, 6.333]
1     (1.987, 6.333]
2     (1.987, 6.333]
3    (6.333, 10.667]
4     (10.667, 15.0]
5     (1.987, 6.333]
6     (10.667, 15.0]
dtype: category
Categories (3, interval[float64, right]): [(1.987, 6.333] < (6.333, 10.667] < (10.667, 15.0]]

In [23]:
disc2 = pd.cut(s,bins = [1,5,11,16])

In [24]:
disc2

0      (1, 5]
1      (1, 5]
2      (1, 5]
3     (5, 11]
4    (11, 16]
5      (1, 5]
6    (11, 16]
dtype: category
Categories (3, interval[int64, right]): [(1, 5] < (5, 11] < (11, 16]]

In [25]:
disc2 = pd.cut(s,bins = [1,5,11,16],labels = ['s','m','l'])

In [26]:
disc2

0    s
1    s
2    s
3    m
4    l
5    s
6    l
dtype: category
Categories (3, object): ['s' < 'm' < 'l']

#### Permutations and random sampling.

In [116]:
# np.random.permutation(n) returnsa random permutations of integers 0 to (n-1).
new = np.random.permutation(3)

In [117]:
df5.iloc[new,:]

A  B
y  2  3
x  1  2
z  3  6